name = "boar-park"
compatibility_date = "2025-03-21"

pages_build_output_dir = "frontend/"

[[d1_databases]]
binding = "BoarDB"
database_name = "boar-park-db"
database_id = "5c36b70f-e6c2-4b33-a9f4-fcfd12039a86"
