-- Boar Park - Full Database Schema
-- Generated from local database on 2026-02-12

-- ============================================================
-- FUNCTIONS (needed by triggers and materialized views)
-- ============================================================

CREATE FUNCTION refresh_all_stats() RETURNS void
    LANGUAGE plpgsql AS $$
BEGIN
    REFRESH MATERIALIZED VIEW movie_stats;
    REFRESH MATERIALIZED VIEW hero_stats;
    REFRESH MATERIALIZED VIEW tag_stats;
END;
$$;

CREATE FUNCTION refresh_hero_stats_trigger() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY hero_stats;
    RETURN NULL;
END;
$$;

CREATE FUNCTION refresh_movie_stats_trigger() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY movie_stats;
    RETURN NULL;
END;
$$;

-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE games (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE,
    slug varchar(255) NOT NULL UNIQUE,
    type varchar(50) NOT NULL CHECK (type IN ('CARDS', 'BOARDS')),
    last_update_dt timestamptz DEFAULT CURRENT_TIMESTAMP,
    last_update_user varchar(255) DEFAULT 'admin'
);

CREATE TABLE heroes (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    industry varchar(50) NOT NULL,
    game_id bigint NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    last_update_dt timestamptz DEFAULT CURRENT_TIMESTAMP,
    last_update_user varchar(255) DEFAULT 'admin',
    UNIQUE(game_id, name)
);

CREATE TABLE movies (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_id bigint NOT NULL REFERENCES heroes(id) ON DELETE CASCADE,
    title varchar(255) NOT NULL,
    need_review boolean DEFAULT false,
    last_update_dt timestamptz DEFAULT CURRENT_TIMESTAMP,
    last_update_user varchar(255) DEFAULT 'admin',
    locked boolean DEFAULT false NOT NULL
);

CREATE TABLE cards (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id bigint REFERENCES movies(id) ON DELETE CASCADE,
    hero_id bigint NOT NULL REFERENCES heroes(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    type varchar(20) NOT NULL CHECK (type IN ('HERO', 'VILLAIN', 'SR1', 'SR2', 'WC')),
    call_sign text,
    ability_text text NOT NULL,
    ability_text2 text,
    need_review boolean DEFAULT false,
    last_update_dt timestamptz DEFAULT CURRENT_TIMESTAMP,
    last_update_user varchar(255) DEFAULT 'admin'
);

CREATE TABLE tags (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE card_tags (
    card_id bigint NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
    tag_id bigint NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (card_id, tag_id)
);

-- Auth tables

CREATE TABLE users (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(32) NOT NULL UNIQUE,
    email varchar(255) NOT NULL UNIQUE,
    password_hash varchar(255),
    is_verified boolean DEFAULT false NOT NULL,
    status varchar(16) DEFAULT 'pending' NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
);

CREATE TABLE roles (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(32) NOT NULL UNIQUE
);

CREATE TABLE user_game_roles (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    game_id integer REFERENCES games(id) ON DELETE CASCADE,
    role_id integer NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    UNIQUE(user_id, game_id, role_id)
);

CREATE TABLE refresh_tokens (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token varchar(255) NOT NULL UNIQUE,
    expires_at timestamp NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL
);

CREATE TABLE password_resets (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token varchar(255) NOT NULL UNIQUE,
    expires_at timestamp NOT NULL,
    used boolean DEFAULT false NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_heroes_game_id ON heroes(game_id);
CREATE INDEX idx_movies_hero_id ON movies(hero_id);
CREATE UNIQUE INDEX idx_movies_hero_title ON movies(hero_id, title);
CREATE UNIQUE INDEX idx_cards_hero_movie_name ON cards(hero_id, movie_id, name);
CREATE INDEX idx_card_tags_card_id ON card_tags(card_id);
CREATE INDEX idx_card_tags_tag_id ON card_tags(tag_id);

-- ============================================================
-- MATERIALIZED VIEWS
-- ============================================================

CREATE MATERIALIZED VIEW movie_stats AS
SELECT
    m.id AS movie_id,
    m.hero_id,
    m.title,
    m.need_review,
    m.locked,
    m.last_update_user,
    m.last_update_dt,
    count(c.id) AS total_cards,
    count(CASE WHEN c.need_review = true THEN 1 END) AS total_cards_need_review,
    CASE
        WHEN count(c.id) < 5 OR count(CASE WHEN c.need_review = true THEN 1 END) > 0 THEN false
        ELSE true
    END AS done
FROM movies m
LEFT JOIN cards c ON c.movie_id = m.id
GROUP BY m.id, m.hero_id, m.title, m.need_review, m.locked, m.last_update_user, m.last_update_dt
WITH NO DATA;

CREATE UNIQUE INDEX idx_movie_stats_movie_id ON movie_stats(movie_id);
CREATE INDEX idx_movie_stats_hero_id ON movie_stats(hero_id);
CREATE INDEX idx_movie_stats_done ON movie_stats(done);

CREATE MATERIALIZED VIEW hero_stats AS
SELECT
    h.id AS hero_id,
    h.name,
    h.industry,
    h.game_id,
    count(DISTINCT m.id) AS total_movies,
    count(DISTINCT CASE WHEN ms.done = false THEN m.id END) AS pending_movies,
    count(DISTINCT c.id) AS total_cards,
    count(DISTINCT CASE WHEN c.need_review = true THEN c.id END) AS cards_need_review
FROM heroes h
LEFT JOIN movies m ON m.hero_id = h.id
LEFT JOIN movie_stats ms ON ms.movie_id = m.id
LEFT JOIN cards c ON c.hero_id = h.id
GROUP BY h.id, h.name, h.industry, h.game_id
WITH NO DATA;

CREATE UNIQUE INDEX idx_hero_stats_hero_id ON hero_stats(hero_id);
CREATE INDEX idx_hero_stats_game_id ON hero_stats(game_id);
CREATE INDEX idx_hero_stats_industry ON hero_stats(industry);

CREATE MATERIALIZED VIEW tag_stats AS
SELECT
    t.id AS tag_id,
    t.name AS tag_name,
    count(ct.card_id) AS card_count,
    count(DISTINCT c.hero_id) AS hero_count
FROM tags t
LEFT JOIN card_tags ct ON ct.tag_id = t.id
LEFT JOIN cards c ON c.id = ct.card_id
GROUP BY t.id, t.name
WITH NO DATA;

CREATE UNIQUE INDEX idx_tag_stats_tag_id ON tag_stats(tag_id);
CREATE INDEX idx_tag_stats_card_count ON tag_stats(card_count DESC);

-- ============================================================
-- TRIGGERS
-- ============================================================

CREATE TRIGGER trigger_refresh_movie_stats_on_movie_change
    AFTER INSERT OR UPDATE OR DELETE ON movies
    FOR EACH STATEMENT EXECUTE FUNCTION refresh_movie_stats_trigger();

CREATE TRIGGER trigger_refresh_movie_stats_on_card_change
    AFTER INSERT OR UPDATE OR DELETE ON cards
    FOR EACH STATEMENT EXECUTE FUNCTION refresh_movie_stats_trigger();

CREATE TRIGGER trigger_refresh_hero_stats_on_hero_change
    AFTER INSERT OR UPDATE OR DELETE ON heroes
    FOR EACH STATEMENT EXECUTE FUNCTION refresh_hero_stats_trigger();

CREATE TRIGGER trigger_refresh_hero_stats_on_movie_change
    AFTER INSERT OR UPDATE OR DELETE ON movies
    FOR EACH STATEMENT EXECUTE FUNCTION refresh_hero_stats_trigger();

-- ============================================================
-- SEED DATA
-- ============================================================

INSERT INTO games (id, name, slug, type) VALUES
    (1, 'Talkies', 'talkies', 'CARDS');
SELECT setval('games_id_seq', 1, true);

INSERT INTO roles (id, name) VALUES
    (1, 'admin'),
    (2, 'editor'),
    (3, 'designer'),
    (4, 'reviewer'),
    (5, 'viewer');
SELECT setval('roles_id_seq', 5, true);

-- Refresh materialized views with initial (empty) data
REFRESH MATERIALIZED VIEW movie_stats;
REFRESH MATERIALIZED VIEW hero_stats;
REFRESH MATERIALIZED VIEW tag_stats;
